[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "FTST"
version = "0.1.0"
packages = ["FTST"]
package-dir = {""="src/python"}

[tool.setuptools.package-data]
FTST = ["*.so"]
